stages:
    - sast
    - build

sast:
    stage: sast
include:
    - template: Security/SAST.gitlab-ci.yml

publish:
    image: docker:20.10.16
    stage: build
    services:
        - docker:20.10.16-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - IMAGE_NAME=ctezlifrn/avamoodle:$CI_COMMIT_TAG
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
    only:
        - tags
