stages:
  - sast
  - build

sast:
  stage: sast
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - IMAGE_NAME=$CI_REGISTRY_IMAGE:`head -1 Dockerfile | cut -c23-`-deploy$CI_COMMIT_TAG
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - tags
