services:

  cache:
    image: redis:7.0.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  ava:
    image: registry.gitlab.com/zl-installs/zl-ava-installs/moodle:401-002
    restart: always
    ports:
      - '7080:80'
    env_file:
      - .env
    volumes:
      # Data
      - './volumes/ava/moodledata/filedir:/var/moodledata/filedir'
    depends_on:
      db:
        condition: service_healthy
