services:
    cache:
        image: redis:7.2-alpine
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 3s
            timeout: 3s
            retries: 3
            start_period: 10s

    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=changeme
        volumes:
            # init settings, executed only on deploy
            - "./src/postgres/:/docker-entrypoint-initdb.d"
            # database data
            - "~/projetos/IFRN/ava/volumes/db_data:/var/lib/postgresql/data"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 3s
            timeout: 3s
            retries: 3
            start_period: 10s

    nginx:
        image: nginx:1.23.3-alpine
        volumes:
            # confs
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/error_pages:/usr/share/nginx/error_pages
        ports:
            - 80:80
        depends_on:
            - painel
            # - ava
