services:

  cache:
    image: redis:7.0.2-alpine
    ports:
      - '6379:6379'
    env_file:
      - .env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  ava:
    image: registry.gitlab.com/zl-installs/zl-ava-installs/moodle:401-020
    ports:
      - '7080:80'
    env_file:
      - .env
    volumes:
      # Source
      # - '../moodle__image/src/php/config.php:/var/www/html/config.php'
      # - '../moodle__local_suap:/var/www/html/local/suap'
      # - '../moodle__block_suapattendance:/var/www/html/blocks/suapattendance'
      # - '../moodle__theme_maeve:/var/www/html/theme/maeve'
      
      # Data
      - './volumes/ava/moodledata:/var/moodledata'
    depends_on:
      db:
        condition: service_healthy

  cron:
    image: registry.gitlab.com/zl-installs/zl-ava-installs/moodle:401-020
    env_file:
      - .env
    volumes:
      # Source
      # - '../moodle__image/src/php/config.php:/var/www/html/config.php'
      # - '../moodle__local_suap:/var/www/html/local/suap'
      # - '../moodle__block_suapattendance:/var/www/html/blocks/suapattendance'
      # - '../moodle__theme_maeve:/var/www/html/theme/maeve'
      # Data
      - './volumes/ava/moodledata:/var/moodledata'
      - './volumes/ava/custom_log:/var/custom_log'      
    depends_on:
      db:
        condition: service_healthy
    user: root
    command: exec-cron.sh
