#!/bin/bash
source /var/dockers/_/functions

backup_log="/var/log/backup.log"
backup_dir="/media/fs_ead"
dia_semana=`date +'%w'`

tipo="ava"
subtipo="sql"

function backup_all() {

   # cp /etc/grafana-agent.yaml /var/dockers/sysconfig/
   # cp /usr/lib/systemd/system/grafana-agent.service /var/dockers/sysconfig/
   cp /etc/fstab  /var/dockers/sysconfig/
   cp /var/spool/cron/* /var/dockers/sysconfig/crontabs/
   cd /var/dockers/
   git add .
   git commit --allow-empty -m 'upd: settings'
   git push

   # for service in 'teste'; do
   #    filename="$tipo.$service.$subtipo.$dia_semana.pgdump"

   #    echo_log 'Dumping' $filename
   #    PGPASSWORD=f3Tq7KStdvcse6kVpMrKM7ULZp3T3pTwooq pg_dump -Fc -v -h `hostname` -d postgres -U postgres -f $backup_dir/$tipo-$service/$filename  \
   #    && send_to_sentry $service $tipo $subtipo $filename
   # done

   # for service in 'portal'; do
   #    filename="$tipo.$service.$subtipo.$dia_semana.pgdump"

   #    echo_log 'Dumping' $filename
   #    docker compose exec ${service}db pg_dump -Fc -v -U $service > $backup_dir/$tipo-teste$service/$filename  \
   #    && send_to_sentry $service $tipo $subtipo $filename
   # done
}

backup_all >> $backup_log
# backup_all
