#!/usr/bin/env bash
# export SENTRY_DSN=https:/98c086126a174ac9abd54036490e71a9@o289006.ingest.sentry.io/6033863
# eval "$(sentry-cli bash-hook)"

source /var/dockers/.env

GREEN_COLOR='\033[1;32m'
ORANGE_COLOR='\033[0;33m'
RED_COLOR='\033[0;31m'
BLUE_COLOR='\033[1;34m'
NO_COLOR='\033[0m'

SERVICE_NAME=$(basename $(dirname $0))

pwd=$(pwd -P)

function echo_warning() {
  echo ${@:3} -e "$ORANGE_COLOR WARN: $(date +\"%F\ %T\") $1$NO_COLOR"
}

function echo_danger() {
  echo ${@:3} -e "$RED_COLOR DANG: $(date +\"%F\ %T\") $1$NO_COLOR"
}

function echo_info() {
  echo ${@:3} -e "$BLUE_COLOR INFO: $(date +\"%F\ %T\") $1$NO_COLOR"
}

function echo_success() {
  echo ${@:3} -e "$GREEN_COLOR SUCC: $(date +\"%F\ %T\") $1$NO_COLOR"
}

function echo_log(){
    message=$1
    filename=$2
    echo "`date` - `hostname` - $message:$filename" \ 
}

function send_to_sentry() {
    service=$1
    tipo=$2
    subtipo=$3
    filename=$4

    echo_log 'Comunicando' $filename
    sentry-cli send-event -l info -m "Backup done: $filename" -t service:$service -t tipo:$tipo -t subtipo:$subtipo -t dia_semana:$dia_semana
}
