#!/usr/bin/env bash
source /var/dockers/_/functions
source ./confs/enabled/$SERVICE_NAME.env

echo_info "Aguardando a base de dados..."
until _/$SERVICE_NAME/exec psql -U postgres -d postgres -A -c '\l'>/dev/null 2>&1; do
  E=$(docker compose logs --tail 1 $SERVICE_NAME | tail -1)
  echo_warning "Postgres is unavailable - sleeping. ERROR: $E"
  sleep 1
done
echo_success "Conectado com sucesso!"
